import type { TripTemplate, PreTripChecklistItem } from '../../types';

type RawCheck = Omit<PreTripChecklistItem, 'id'>;

const baseChecklist = (extras: RawCheck[] = []): RawCheck[] => ([
    { task: 'Confirmar reserva de transporte', category: 'transport', completed: false, priority: 'high' },
    { task: 'Confirmar alojamiento', category: 'booking', completed: false, priority: 'high' },
    { task: 'Cargar el celular y powerbank', category: 'communication', completed: false, priority: 'medium' },
    { task: 'Revisar pronóstico del clima', category: 'other', completed: false, priority: 'medium' },
    ...extras,
]);

const internationalChecklist = (): RawCheck[] => ([
    ...baseChecklist(),
    { task: 'Verificar pasaporte (vigencia mín. 6 meses)', category: 'documents', completed: false, priority: 'high' },
    { task: 'Visa o documentos migratorios', category: 'documents', completed: false, priority: 'high' },
    { task: 'Comprar seguro de viaje', category: 'documents', completed: false, priority: 'high' },
    { task: 'Vacunas requeridas', category: 'health', completed: false, priority: 'high' },
    { task: 'Activar roaming o comprar SIM', category: 'communication', completed: false, priority: 'medium' },
    { task: 'Notificar al banco (uso en exterior)', category: 'finances', completed: false, priority: 'high' },
    { task: 'Cambiar dinero / Tarjeta multidivisa', category: 'finances', completed: false, priority: 'high' },
    { task: 'Copia digital de pasaporte y docs', category: 'documents', completed: false, priority: 'high' },
    { task: 'Descargar mapas offline', category: 'communication', completed: false, priority: 'medium' },
]);

export const DEFAULT_TRIP_TEMPLATES: TripTemplate[] = [
    {
        id: 'default-beach-weekend',
        name: 'Fin de semana en la playa 🏖️',
        description: 'Para escapadas cortas: 3 días, todo lo esencial sin sobrecargar.',
        type: 'beach',
        durationDays: 3,
        createdAt: 0,
        packingItems: [
            { name: 'Traje de baño', category: 'Ropa', packed: false, priority: 'essential', quantity: 2 },
            { name: 'Camisetas', category: 'Ropa', packed: false, priority: 'essential', quantity: 3 },
            { name: 'Shorts', category: 'Ropa', packed: false, priority: 'essential', quantity: 2 },
            { name: 'Vestido / Sundress', category: 'Ropa', packed: false, priority: 'recommended', quantity: 1 },
            { name: 'Ropa interior', category: 'Ropa', packed: false, priority: 'essential', quantity: 4 },
            { name: 'Sandalias', category: 'Calzado', packed: false, priority: 'essential', quantity: 1 },
            { name: 'Tenis cómodos', category: 'Calzado', packed: false, priority: 'recommended', quantity: 1 },
            { name: 'Protector solar SPF 50+', category: 'Higiene', packed: false, priority: 'essential' },
            { name: 'After-sun / Aloe vera', category: 'Higiene', packed: false, priority: 'recommended' },
            { name: 'Cepillo y pasta dental', category: 'Higiene', packed: false, priority: 'essential' },
            { name: 'Desodorante', category: 'Higiene', packed: false, priority: 'essential' },
            { name: 'Repelente de mosquitos', category: 'Higiene', packed: false, priority: 'recommended' },
            { name: 'Gafas de sol', category: 'Accesorios', packed: false, priority: 'essential' },
            { name: 'Sombrero / Gorra', category: 'Accesorios', packed: false, priority: 'recommended' },
            { name: 'Toalla de playa', category: 'Accesorios', packed: false, priority: 'essential' },
            { name: 'Mochila / Bolso de playa', category: 'Accesorios', packed: false, priority: 'essential' },
            { name: 'Cargador de teléfono', category: 'Electrónicos', packed: false, priority: 'essential' },
            { name: 'Powerbank', category: 'Electrónicos', packed: false, priority: 'recommended' },
            { name: 'Documento de identidad', category: 'Documentos', packed: false, priority: 'essential' },
        ],
        checklistItems: baseChecklist([
            { task: 'Reservar mesa para cena especial', category: 'booking', completed: false, priority: 'low' },
            { task: 'Cargar playlist offline', category: 'other', completed: false, priority: 'low' },
        ]),
        itineraryActivities: [
            {
                dayNumber: 1, activities: [
                    { time: '14:00', description: 'Llegada y check-in al hotel', completed: false, type: 'rest', duration: 60 },
                    { time: '17:00', description: 'Caminar por la playa al atardecer', completed: false, type: 'tour' },
                    { time: '20:00', description: 'Cena en restaurante local', completed: false, type: 'food', estimatedCost: 60000 },
                ]
            },
            {
                dayNumber: 2, activities: [
                    { time: '08:30', description: 'Desayuno', completed: false, type: 'food' },
                    { time: '10:00', description: 'Día de playa / piscina', completed: false, type: 'rest', duration: 240 },
                    { time: '14:00', description: 'Almuerzo frente al mar', completed: false, type: 'food', estimatedCost: 50000 },
                    { time: '17:00', description: 'Tiempo libre / siesta', completed: false, type: 'rest' },
                    { time: '20:00', description: 'Cena y cocteles', completed: false, type: 'food', estimatedCost: 80000 },
                ]
            },
            {
                dayNumber: 3, activities: [
                    { time: '09:00', description: 'Desayuno', completed: false, type: 'food' },
                    { time: '11:00', description: 'Última caminata o compras', completed: false, type: 'shopping' },
                    { time: '13:00', description: 'Check-out y regreso', completed: false, type: 'transport' },
                ]
            },
        ],
    },
    {
        id: 'default-international-2weeks',
        name: 'Internacional 2 semanas 🌍',
        description: 'Viaje largo al exterior con todos los essentials de viaje internacional.',
        type: 'international',
        durationDays: 14,
        createdAt: 0,
        packingItems: [
            { name: 'Pasaporte', category: 'Documentos', packed: false, priority: 'essential' },
            { name: 'Visa / Documentos migratorios', category: 'Documentos', packed: false, priority: 'essential' },
            { name: 'Seguro de viaje (impreso + digital)', category: 'Documentos', packed: false, priority: 'essential' },
            { name: 'Tarjeta de crédito multidivisa', category: 'Documentos', packed: false, priority: 'essential' },
            { name: 'Efectivo en moneda local', category: 'Documentos', packed: false, priority: 'essential' },
            { name: 'Copia digital de todos los docs', category: 'Documentos', packed: false, priority: 'essential' },
            { name: 'Camisetas', category: 'Ropa', packed: false, priority: 'essential', quantity: 7 },
            { name: 'Pantalones / Faldas / Vestidos', category: 'Ropa', packed: false, priority: 'essential', quantity: 5 },
            { name: 'Ropa interior', category: 'Ropa', packed: false, priority: 'essential', quantity: 14 },
            { name: 'Calcetines', category: 'Ropa', packed: false, priority: 'essential', quantity: 14 },
            { name: 'Pijama', category: 'Ropa', packed: false, priority: 'essential', quantity: 2 },
            { name: 'Chaqueta abrigada', category: 'Ropa', packed: false, priority: 'recommended' },
            { name: 'Chaqueta impermeable / Paraguas plegable', category: 'Ropa', packed: false, priority: 'recommended' },
            { name: 'Outfit elegante (cena, eventos)', category: 'Ropa', packed: false, priority: 'recommended' },
            { name: 'Zapatos cómodos para caminar', category: 'Calzado', packed: false, priority: 'essential' },
            { name: 'Zapatos de vestir', category: 'Calzado', packed: false, priority: 'recommended' },
            { name: 'Sandalias', category: 'Calzado', packed: false, priority: 'optional' },
            { name: 'Adaptador universal', category: 'Electrónicos', packed: false, priority: 'essential' },
            { name: 'Cargador de teléfono', category: 'Electrónicos', packed: false, priority: 'essential' },
            { name: 'Powerbank de alta capacidad', category: 'Electrónicos', packed: false, priority: 'essential' },
            { name: 'Audífonos', category: 'Electrónicos', packed: false, priority: 'recommended' },
            { name: 'Cámara + cargador', category: 'Electrónicos', packed: false, priority: 'optional' },
            { name: 'Kit de higiene completo', category: 'Higiene', packed: false, priority: 'essential' },
            { name: 'Botiquín de viaje', category: 'Higiene', packed: false, priority: 'essential' },
            { name: 'Medicamentos personales', category: 'Medicamentos', packed: false, priority: 'essential' },
            { name: 'Protector solar', category: 'Higiene', packed: false, priority: 'essential' },
            { name: 'Mochila de día', category: 'Accesorios', packed: false, priority: 'essential' },
            { name: 'Candado para maleta', category: 'Accesorios', packed: false, priority: 'recommended' },
            { name: 'Bolsas de compresión / Empaque', category: 'Accesorios', packed: false, priority: 'recommended' },
        ],
        checklistItems: internationalChecklist(),
    },
    {
        id: 'default-business-trip',
        name: 'Viaje de negocios 💼',
        description: 'Para 2-4 días de trabajo en otra ciudad. Lo justo, sin pesar.',
        type: 'business',
        durationDays: 3,
        createdAt: 0,
        packingItems: [
            { name: 'Trajes / Conjuntos formales', category: 'Ropa', packed: false, priority: 'essential', quantity: 3 },
            { name: 'Camisas / Blusas', category: 'Ropa', packed: false, priority: 'essential', quantity: 3 },
            { name: 'Ropa interior', category: 'Ropa', packed: false, priority: 'essential', quantity: 4 },
            { name: 'Pijama', category: 'Ropa', packed: false, priority: 'essential' },
            { name: 'Ropa casual (después del trabajo)', category: 'Ropa', packed: false, priority: 'recommended' },
            { name: 'Zapatos de vestir', category: 'Calzado', packed: false, priority: 'essential' },
            { name: 'Tenis cómodos', category: 'Calzado', packed: false, priority: 'recommended' },
            { name: 'Laptop + cargador', category: 'Electrónicos', packed: false, priority: 'essential' },
            { name: 'Mouse y accesorios', category: 'Electrónicos', packed: false, priority: 'recommended' },
            { name: 'Adaptador de enchufe', category: 'Electrónicos', packed: false, priority: 'recommended' },
            { name: 'Cargador de celular + powerbank', category: 'Electrónicos', packed: false, priority: 'essential' },
            { name: 'Tarjetas de presentación', category: 'Documentos', packed: false, priority: 'recommended' },
            { name: 'Cuaderno y bolígrafo', category: 'Accesorios', packed: false, priority: 'recommended' },
            { name: 'Documento de identidad', category: 'Documentos', packed: false, priority: 'essential' },
            { name: 'Agenda / Itinerario impreso', category: 'Documentos', packed: false, priority: 'optional' },
            { name: 'Maquillaje / Kit de aseo express', category: 'Higiene', packed: false, priority: 'essential' },
        ],
        checklistItems: baseChecklist([
            { task: 'Imprimir agenda y materiales', category: 'documents', completed: false, priority: 'high' },
            { task: 'Confirmar reuniones con clientes', category: 'other', completed: false, priority: 'high' },
            { task: 'Revisar presentación final', category: 'other', completed: false, priority: 'high' },
            { task: 'Cargar laptop al 100%', category: 'communication', completed: false, priority: 'medium' },
        ]),
    },
    {
        id: 'default-mountain-getaway',
        name: 'Escapada a la montaña 🏔️',
        description: '3-5 días de naturaleza, senderismo y desconexión.',
        type: 'mountain',
        durationDays: 4,
        createdAt: 0,
        packingItems: [
            { name: 'Botas de senderismo', category: 'Calzado', packed: false, priority: 'essential' },
            { name: 'Tenis para descanso', category: 'Calzado', packed: false, priority: 'recommended' },
            { name: 'Chaqueta impermeable', category: 'Ropa', packed: false, priority: 'essential' },
            { name: 'Capas térmicas', category: 'Ropa', packed: false, priority: 'essential', quantity: 2 },
            { name: 'Pantalones de trekking', category: 'Ropa', packed: false, priority: 'essential', quantity: 2 },
            { name: 'Camisetas técnicas', category: 'Ropa', packed: false, priority: 'essential', quantity: 4 },
            { name: 'Calcetines técnicos', category: 'Ropa', packed: false, priority: 'essential', quantity: 5 },
            { name: 'Ropa interior térmica', category: 'Ropa', packed: false, priority: 'essential', quantity: 4 },
            { name: 'Gorro y guantes', category: 'Accesorios', packed: false, priority: 'essential' },
            { name: 'Mochila de trekking', category: 'Accesorios', packed: false, priority: 'essential' },
            { name: 'Cantimplora / Termo', category: 'Accesorios', packed: false, priority: 'essential' },
            { name: 'Linterna frontal', category: 'Electrónicos', packed: false, priority: 'recommended' },
            { name: 'Powerbank', category: 'Electrónicos', packed: false, priority: 'essential' },
            { name: 'Botiquín completo', category: 'Higiene', packed: false, priority: 'essential' },
            { name: 'Protector solar y labial', category: 'Higiene', packed: false, priority: 'essential' },
            { name: 'Repelente', category: 'Higiene', packed: false, priority: 'recommended' },
            { name: 'Snacks energéticos', category: 'Otros', packed: false, priority: 'recommended' },
        ],
        checklistItems: baseChecklist([
            { task: 'Verificar estado del clima', category: 'other', completed: false, priority: 'high' },
            { task: 'Revisar rutas y senderos', category: 'other', completed: false, priority: 'high' },
            { task: 'Avisar a alguien la ruta planeada', category: 'communication', completed: false, priority: 'high' },
            { task: 'Cargar mapas offline', category: 'communication', completed: false, priority: 'high' },
        ]),
    },
    {
        id: 'default-city-break',
        name: 'City Break 🏙️',
        description: '3-5 días explorando una ciudad: museos, restaurantes y caminatas.',
        type: 'city',
        durationDays: 4,
        createdAt: 0,
        packingItems: [
            { name: 'Camisetas / Blusas', category: 'Ropa', packed: false, priority: 'essential', quantity: 4 },
            { name: 'Pantalones / Jeans', category: 'Ropa', packed: false, priority: 'essential', quantity: 2 },
            { name: 'Vestido / Outfit nice', category: 'Ropa', packed: false, priority: 'recommended' },
            { name: 'Ropa interior', category: 'Ropa', packed: false, priority: 'essential', quantity: 5 },
            { name: 'Calcetines', category: 'Ropa', packed: false, priority: 'essential', quantity: 5 },
            { name: 'Chaqueta ligera', category: 'Ropa', packed: false, priority: 'recommended' },
            { name: 'Pijama', category: 'Ropa', packed: false, priority: 'essential' },
            { name: 'Tenis cómodos para caminar', category: 'Calzado', packed: false, priority: 'essential' },
            { name: 'Zapatos para salir de noche', category: 'Calzado', packed: false, priority: 'optional' },
            { name: 'Cargador de celular', category: 'Electrónicos', packed: false, priority: 'essential' },
            { name: 'Powerbank', category: 'Electrónicos', packed: false, priority: 'recommended' },
            { name: 'Audífonos', category: 'Electrónicos', packed: false, priority: 'recommended' },
            { name: 'Cámara o celular con buena cámara', category: 'Electrónicos', packed: false, priority: 'recommended' },
            { name: 'Documento de identidad', category: 'Documentos', packed: false, priority: 'essential' },
            { name: 'Tarjeta de crédito + efectivo', category: 'Documentos', packed: false, priority: 'essential' },
            { name: 'Mochila / Bolso de día', category: 'Accesorios', packed: false, priority: 'essential' },
            { name: 'Paraguas plegable', category: 'Accesorios', packed: false, priority: 'optional' },
            { name: 'Kit de higiene', category: 'Higiene', packed: false, priority: 'essential' },
            { name: 'Maquillaje', category: 'Higiene', packed: false, priority: 'recommended' },
        ],
        checklistItems: baseChecklist([
            { task: 'Reservar entradas a atracciones', category: 'booking', completed: false, priority: 'medium' },
            { task: 'Reservar restaurantes populares', category: 'booking', completed: false, priority: 'low' },
            { task: 'Descargar app del transporte público', category: 'communication', completed: false, priority: 'medium' },
            { task: 'Hacer lista de lugares a visitar', category: 'other', completed: false, priority: 'low' },
        ]),
    },
];
